### ISSUE TITLE
header color

### ISSUE THREAD

**Issue by hardin47** [ginolhac/unilur#3] opened 2023-12-26 23:01 UTC
I'm using the **unilur** quarto extension to write assignments within a course website.  When I downloaded the extension, all of the custom colors changed to green.  I was able to change the solution boxes by editing `unliur.css`.  But I can't change the rest of the website coloring back.  What is happening behind the scenes that forces, for example, the navbar to be green?  Is there any way for me to change colors and fonts?  (I've tried putting nav colors into `unilur.css`, but that doesn't change anything).  Thanks for your help!

**Comment by ginolhac** [comment] 2023-12-27 17:54
Hello,
Thanks for your message.
I am currently on vacation and will look into this when I am back.
I don't see why my css would change the navbar, it is supposed to only act on one call-out. But I might be mistaken.
Best

**Comment by hardin47** [comment] 2023-12-28 02:49
Enjoy your vacation!!!

But for when you come back...  I've installed the extension of unilur (not the R package).  Yes, I am able to change the file "_extensions/ginolhac/unilur/unilur.css" to change the color of the call-out boxes!

However, somehow when I install the unilur extension and then render any quarto file for my website, the following file changes: "_site/site_libs/bootstrap/bootstrap.min.css". I think that's how all the colors and fonts are getting messed up.  I can't just change "bootstrap.min.css" back to how it was because the file gets re-created with every render (the `_site` folder is where all the rendered files live).

If I uninstall the unilur extension, the "bootstrap.min.css" file goes back to what I had set in my own website .css file, and the colors and fonts seem fine.

Thanks for your help!!!!

**Comment by ginolhac** [comment] 2024-01-04 08:47
Hello,
I cannot reproduce your problem, but I think a good lead is the quarto version. I am using the pre-release for several months (> v1.4), do you use Quarto version 1.3?
If yes, it is worth updating, version 1.4 (https://quarto.org/docs/download/) should be the standard anytime soon.

**Comment by hardin47** [comment] 2024-01-04 13:55
I figured out a workaround.  All of the files live in the same R project.  When I compile an assignment using **unilur**, the colors of all files (including all the base website files) change to green, presumably because `_site/site_libs/bootstrap/bootstrap.min.css` changes.  But then if I compile one of the original files (e.g., `index.qmd`), everything (including the assignments) goes back to my original palette, and `_site/site_libs/bootstrap/bootstrap.min.css` goes back to the original settings.

I'm sorry that I can't provide a reproducible example!

Also, you may be right that updating to Quarto 1.4 would help (I am using 1.3).  However, I need things to stay constant for the next two weeks, so I can't update anything until then.  

Thanks for your help!  I'll let you know if I get any additional relevant information.

**Comment by ginolhac** [comment] 2024-01-04 14:11
thanks! yes please keep me posted with the update to 1.4. I might need to ask for a higher requirement.
Of note, I just make a new version (0.0.4) that uses a custom callout and leave the caution callout alone. Meaning the CSS is specific to something in unilur. You could maybe also test that if you wish.

**Comment by ginolhac** [comment] 2024-03-19 08:59
closing as quarto v1.4 is now released. Feel free to reopen if the error is still ongoing

**Closed by ginolhac** 2024-03-19 08:59 UTC
